bundler_args: ""
before_install:
  - sudo apt-get update
  - sudo apt-get install -y nodejs php5
  - npm install -g coffeelint
  - rvm default do gem install execjs
  - git config --global user.name "Pre Commit"
  - git config --global user.email "pre-commit+travis@example.com"
language: ruby
rvm:
  - ruby-1.9.3
  - ruby-2.0.0
  - ruby-2.1
  - jruby
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby
