sudo: false
addons:
  apt:
    packages:
    - php5
bundler_args: ""
before_install:
  - npm install -g coffeelint
  - rvm default do gem install execjs
  - git config --global user.name "Pre Commit"
  - git config --global user.email "pre-commit+travis@example.com"
  - gem update bundler
cache:
 - bundler
 - npm
language: ruby
rvm:
  - jruby
  - 2.0.0
  - 2.1.9
  - 2.2.5
  - 2.3.1
matrix:
  fast_finish: true
