bundler_args: ""
before_install:
  - sudo apt-get update
  - sudo apt-get install -y nodejs php5
  - rvm default do gem install execjs
  - git config --global user.name "Pre Commit"
  - git config --global user.email "pre-commit+travis@example.com"
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
matrix:
  fast_finish: true
